---
name: 🐞 Feature request
about: new possibility in the UI
title: 'Feature req'
labels: enhancement
assignees: ''

---

<!--
Note: Please search to see if an issue already exists for the improvement you're about to suggest!
-->

### Your suggestions:
<!-- A concise description of what you would like to see improved or added. -->
